import { tsbutton } from "./tsbutton/button.js";
import { list } from "./tsbutton/list.js";
import { text } from "./tsbutton/text.js";
import { form } from "./autogeneratedform/form.js";

const threeStateButtonView = {
    padding:15,
    rows:[
        { cols:[ text, tsbutton ] },
        list,
    ]
};

const autogeneratedform = {
    padding:30,
    rows:[
        form,
    ]
};

export const accordion = { 
    view:"accordion",
    padding:15,
    margin:30,
    rows:[ 
        {
            view:"accordionitem",
            header:"Three state button",
            headerHeight:50, 
            headerAlt:"Three state button", 
            body:threeStateButtonView,
        },
        { 
            view:"accordionitem",
            header:"Autogenerated form",
            headerAlt:"Autogenerated form",
            body:autogeneratedform,
        }
    ]
}